Add files via upload

diff --git a/request/menu b/request/menu
--- a/request/menu
+++ b/request/menu
@@ -108,7 +108,7 @@ atualiza_fun () {
 cd $HOME
 tput cuu1 && tput dl1
 msg -bar2
-msg -ama "$(fun_trans "ACTUALIZADOR ADM SCRIPTS"): \033[1;32m[ NEW - ULTIMATE - SCRIPT ]  \033[1;33m[\033[1;34m OFICIAL BY EDDYEPUMAS \033[1;33m] \033[1;31m[\033[1;37mV 7.0\033[1;31m]"
+msg -ama "$(fun_trans "ACTUALIZADOR DE ADM SCRIPT"): \033[1;32m[ NEW - ULTIMATE - SCRIPT ] \033[1;34m OFICIAL BY EDDYEPUMAS \033[1;37mV 7.0"
 msg -verm "$(fun_trans "Al proseguir los datos como el tiempo de uso seran perdidos"): "
 msg -bar2
 while [[ $Key != @(s|S|y|Y|n|N) ]]; do
@@ -302,6 +302,41 @@ selection=999
 selection=$(selection_fun $Numb)
 [[ -e "${SCPfrm}/${script[$selection]}" ]] && rm ${SCPfrm}/${script[$selection]} || return
 }
+#CUENTAS REGISTRAADAS APROX
+#msg -bar
+SSHN="$(grep -c home /etc/passwd)"
+SSH2="$(echo ${SSHN}|bc)-2"
+echo "${SSH2}"|bc > /etc/newadm/ger-user/SSH20.log
+SSH3="$(less /etc/newadm/ger-user/SSH20.log)"
+SSH4="$(echo $SSH3)"
+#FERRAMENTAS
+agregar_ferramenta () {
+tput cuu1 && tput dl1
+msg -bar2
+unset Key
+echo -e "\033[1;31m$(fun_trans "ATENCION"): "
+echo -e "\033[1;33m$(fun_trans "no introduzca una Key de actualizacion aqui")"
+echo -e "\033[1;37m$(fun_trans "Escriba Key para el nuevo recurso") "
+msg -bar2
+while [[ -z $Key ]]; do
+echo -ne "[Key/Link]: " && read Key
+tput cuu1 && tput dl1
+done
+echo -ne "\033[1;37m$(fun_trans "Verificando key"): "
+cd ${SCPfrm}
+curl "$Key" &> /dev/null
+if [[ $? = "0" ]]; then
+echo -e "\033[1;32m $(fun_trans "Link Valido")"
+REC=$(echo $Key|awk -F"/" '{print $NF}')
+echo -ne "\033[1;33m$(fun_trans "Recibiendo Recurso"): \033[1;31m[$REC]"
+wget -O ${SCPfrm}/${REC} $Key &>/dev/null && echo -e "\033[1;31m- \033[1;32m$(fun_trans "Recibido")" && chmod +x ${SCPfrm}/${REC} || echo -e "\033[1;31m- \033[1;31m$(fun_trans "Error al recibir")"
+else
+wget $(ofus "$Key") >/dev/null 2>&1 && echo -e "\033[1;32m $(fun_trans "Key Valida")" || {
+    msg -verm "$(fun_trans "Key invalida")"
+    msg -bar2
+    return 0   
+    }
+fi
 #MONITOR DE SERVICIOS
 monservi_fun () {
 clear
@@ -428,41 +463,6 @@ done
 if [[ "$1" = "moni2" ]]; then
 monitorport_fun
 exit
-fi
-#CUENTAS REGISTRAADAS APROX
-#msg -bar
-SSHN="$(grep -c home /etc/passwd)"
-SSH2="$(echo ${SSHN}|bc)-2"
-echo "${SSH2}"|bc > /etc/newadm/ger-user/SSH20.log
-SSH3="$(less /etc/newadm/ger-user/SSH20.log)"
-SSH4="$(echo $SSH3)"
-#FERRAMENTAS
-agregar_ferramenta () {
-tput cuu1 && tput dl1
-msg -bar2
-unset Key
-echo -e "\033[1;31m$(fun_trans "ATENCION"): "
-echo -e "\033[1;33m$(fun_trans "no introduzca una Key de actualizacion aqui")"
-echo -e "\033[1;37m$(fun_trans "Escriba Key para el nuevo recurso") "
-msg -bar2
-while [[ -z $Key ]]; do
-echo -ne "[Key/Link]: " && read Key
-tput cuu1 && tput dl1
-done
-echo -ne "\033[1;37m$(fun_trans "Verificando key"): "
-cd ${SCPfrm}
-curl "$Key" &> /dev/null
-if [[ $? = "0" ]]; then
-echo -e "\033[1;32m $(fun_trans "Link Valido")"
-REC=$(echo $Key|awk -F"/" '{print $NF}')
-echo -ne "\033[1;33m$(fun_trans "Recibiendo Recurso"): \033[1;31m[$REC]"
-wget -O ${SCPfrm}/${REC} $Key &>/dev/null && echo -e "\033[1;31m- \033[1;32m$(fun_trans "Recibido")" && chmod +x ${SCPfrm}/${REC} || echo -e "\033[1;31m- \033[1;31m$(fun_trans "Error al recibir")"
-else
-wget $(ofus "$Key") >/dev/null 2>&1 && echo -e "\033[1;32m $(fun_trans "Key Valida")" || {
-    msg -verm "$(fun_trans "Key invalida")"
-    msg -bar2
-    return 0   
-    }
 fi
 IP=$(ofus "$Key" | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
 sleep 1s
@@ -850,7 +850,7 @@ msg -bar
 mine_port
 echo ""
 msg -bar
-echo -e "\033[1;31mCUENTAS SSH:\033[1;92m" "$SSH4"
+echo -e "\033[1;31mCUENTAS SSH:" "\033[1;92m $SSH4"
 echo -e "\e[1;31mBADVPN:\e[0m" "$badvpn"
 msg -bar
 msg -ne "$(fun_trans "SISTEMA OPERATIVO"): " && msg -bra "$(os_system)  "
@@ -869,7 +869,7 @@ _hora=$(printf '%(%H:%M:%S)T')
 msg -bar
 msg -ama "$(fun_trans "MANAGER") \033[1;31m[\033[1;32m NEW-ULTIMATE \033[1;31m] \033[1;33m[\033[1;34m OFICIAL BY EDDYEPUMAS \033[1;33m] \033[1;31m[\033[1;37m$_hora\033[1;31m] "
 msg -bar
-menu_func "ADMINISTRAR USUARIOS" "HERRAMIENTAS" "MENU DE INSTALACIONES" "-vd ACTUALIZACION" "-vm DESINSTALAR" "-fi $AutoRun INICIO AUTOMATICO" "CAMBIAR IDIOMA" "CAMBIAR COLORES" "-azc WEB PANEL (SSHPlus)" " -fi ${monitorservi} MONITOR DE SERVICIOS"
+menu_func "ADMINISTRAR USUARIOS" "HERRAMIENTAS" "MENU DE INSTALACIONES" "-vd ACTUALIZACION" "-vm DESINSTALAR" "-fi $AutoRun INICIO AUTOMATICO" "CAMBIAR IDIOMA" "CAMBIAR COLORES" "-azc PANEL WEB (SSHPlus)" " -fi ${monitorservi} MONITOR DE SERVICIOS"
 echo -ne "$(msg -verd "[0]") $(msg -verm2 ">") " && msg -bra "$(fun_trans "\033[1;41mSALIR DEL SCRIPT")"
 msg -bar
 # FIM
